export const headerAdmine={
    general:{
       margin:0,
       padding:0,
       textDecoration:'none',
       listStyle:'none',
       boxSizing:'borderBox',
       fontFamily:'montserrat',
       widht:'100%'
     },
  script:{
       margin:0,
       padding:0,
       backgroundColor:'black',
       height:'60px',
       widht:'100%',
       fontFamily:'verdana',
       fontSize:'15px'
    },
}